title: Phillipe Souza - Freelancer, Desenvolvedor Web e as vezes Designer.
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://phillipesouza.com.br" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Phillipe Souza # add your name
author-img: phillipe-souza-desenvolvedor-web.jpg # add your photo
about-author: I am a web developer focusing on front-end development. # add description
#twitter: # add your Twitter handle
#facebook: # add your Facebook handle
github: phillipesouza # add your Github handle
linkedin: # add your Linkedin handle
email: ph.ll.pesouza@gmail.com # add your Email address

# Disqus
#discus-identifier: phsouza # add your discus identifier

# Tracker
analytics: UA-43029813-2

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
