# ----
# Site

title: Phillipe Souza
url: "https://phillipesouza.com.br"
baseurl: 
google_analytics_key: UA-43029813-2
google_maps_javascript_api_key:
disqus_shortname: phillipesouza

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Freelancer em Marketing digital e desenvolvimento Web. Meu objetivo é ajudar você ampliar a presença digital da sua empresa.
author: 
  name: Phillipe Souza
  email: contato@phillipesouza.com.br
  twitter: # twitter username without the @ symbol
social:
  name: 
  links:
    - 

# -----
# Build

timezone: America/Bahia

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
    works:
      output: true

paginate: 10
paginate_path: "/blog/:num/"

jekyll-archives:
  enabled: ['categories']

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  - 
    scope:
      path: ""
      type: "works"
    values:
      layout: "work"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      _options:
        image:
          width: 2000
          height: 1322
          resize_style: cover
        content:
          width: 1500
          height: 2000
  -
    scope:
      path: "contact-success.html"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "pages"
    values:
      image:
        width: 2000
        height: 1322
        resize_style: cover
      bottom_image:
        width: 2000
        height: 1322
        resize_style: cover

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - Email
  - RSS

_comments:
  description: Text shown when sharing on social media
  blurb: Short bio or description of this person
