backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "images"

collections: # A list of collections the CMS should be able to edit
  - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Posts" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    label_singular: "Post" # Used in the UI, ie: "New Post"
    description: ""
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Título", name: "title", widget: "string", tagname: "h1"}
      - {label: "Categoria", name: "categories", widget: "select", options: ["Blog", "Works"]}
      - {label: "Data de publicação", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mma"}
      - {label: "Miniatura", name: "miniature", widget: "image", required: false, tagname: ""}
      - {label: "Corpo do Texto", name: "body", widget: "markdown"}
    meta:
      - {label: "SEO Descrição", name: "description", widget: "text"}

#  - name: "faq" # Used in routes, ie.: /admin/collections/:slug/edit
#    label: "FAQ" # Used in the UI
#    folder: "_faqs"
#    create: true # Allow users to create new documents in this collection
#    fields: # The fields each document in this collection have
#      - {label: "Pergunta", name: "title", widget: "string", tagname: "h1"}
#      - {label: "Resposta", name: "body", widget: "markdown"}

#  - name: "settings"
#    label: "Configurações"
#    delete: false # Prevent users from deleting documents in this collection
#    editor:
#      preview: false
#    files:
#      - name: "general"
#        label: "Configurações do Site"
#        file: "_data/settings.json"
#        description: "Configurações Gerais do Site"
#        fields:
#          - {label: "Título Global", name: "site_title", widget: "string"}
#          - label: "Configurações de Post"
#            name: posts
#            widget: "object"
#            fields:
#              - {label: "Número de posts na página inicial", name: front_limit, widget: number}
#              - {label: "Autor Primário", name: author, widget: string}
#              - {label: "Default Thumbnail", name: thumb, widget: image, class: "thumb"}
#
#      - name: "authors"
#        label: "Autores"
#        file: "_data/authors.yml"
#        description: "Descrição do Autor"
#        fields:
#          - name: authors
#            label: Authors
#            label_singular: "Autor"
#            widget: list
#            fields:
#              - {label: "Nome", name: "name", widget: "string"}
#              - {label: "Descrição", name: "description", widget: "markdown"}

#  - name: "kitchenSink" # all the things in one entry, for documentation and quick testing
#    label: "Kitchen Sink"
#    folder: "_sink"
#    create: true
#    fields:
#      - label: "Related Post"
#        name: "post"
#        widget: "relationKitchenSinkPost"
#        collection: "posts"
#        searchFields: ["title", "body"]
#        valueField: "title"
#      - {label: "Title", name: "title", widget: "string"}
#      - {label: "Boolean", name: "boolean", widget: "boolean", default: true}
#      - {label: "Text", name: "text", widget: "text"}
#      - {label: "Number", name: "number", widget: "number"}
#      - {label: "Markdown", name: "markdown", widget: "markdown"}
#      - {label: "Datetime", name: "datetime", widget: "datetime"}
#      - {label: "Date", name: "date", widget: "date"}
#      - {label: "Image", name: "image", widget: "image"}
#      - {label: "File", name: "file", widget: "file"}
#      - {label: "Select", name: "select", widget: "select", options: ["a", "b", "c"]}
#      - {label: "Hidden", name: "hidden", widget: "hidden", default: "hidden"}
#      - label: "Object"
#        name: "object"
#        widget: "object"
#        fields:
#          - label: "Related Post"
#            name: "post"
#            widget: "relationKitchenSinkPost"
#            collection: "posts"
#            searchFields: ["title", "body"]
#            valueField: "title"
#          - {label: "String", name: "string", widget: "string"}
#          - {label: "Boolean", name: "boolean", widget: "boolean", default: false}
#          - {label: "Text", name: "text", widget: "text"}
#          - {label: "Number", name: "number", widget: "number"}
#          - {label: "Markdown", name: "markdown", widget: "markdown"}
#          - {label: "Datetime", name: "datetime", widget: "datetime"}
#          - {label: "Date", name: "date", widget: "date"}
#          - {label: "Image", name: "image", widget: "image"}
#          - {label: "File", name: "file", widget: "file"}
#          - {label: "Select", name: "select", widget: "select", options: ["a", "b", "c"]}
#      - label: "List"
#        name: "list"
#        widget: "list"
#        fields:
#          - {label: "String", name: "string", widget: "string"}
#          - {label: "Boolean", name: "boolean", widget: "boolean"}
#          - {label: "Text", name: "text", widget: "text"}
#          - {label: "Number", name: "number", widget: "number"}
#          - {label: "Markdown", name: "markdown", widget: "markdown"}
#          - {label: "Datetime", name: "datetime", widget: "datetime"}
#          - {label: "Date", name: "date", widget: "date"}
#          - {label: "Image", name: "image", widget: "image"}
#          - {label: "File", name: "file", widget: "file"}
#          - {label: "Select", name: "select", widget: "select", options: ["a", "b", "c"]}
#          - label: "Object"
#            name: "object"
#            widget: "object"
#            fields:
#              - {label: "String", name: "string", widget: "string"}
#              - {label: "Boolean", name: "boolean", widget: "boolean"}
#              - {label: "Text", name: "text", widget: "text"}
#              - {label: "Number", name: "number", widget: "number"}
#              - {label: "Markdown", name: "markdown", widget: "markdown"}
#              - {label: "Datetime", name: "datetime", widget: "datetime"}
#              - {label: "Date", name: "date", widget: "date"}
#              - {label: "Image", name: "image", widget: "image"}
#              - {label: "File", name: "file", widget: "file"}
#              - {label: "Select", name: "select", widget: "select", options: ["a", "b", "c"]}
#              - label: "List"
#                name: "list"
#                widget: "list"
#                fields:
#                  - label: "Related Post"
#                    name: "post"
#                    widget: "relationKitchenSinkPost"
#                    collection: "posts"
#                    searchFields: ["title", "body"]
#                    valueField: "title"
#                  - {label: "String", name: "string", widget: "string"}
#                  - {label: "Boolean", name: "boolean", widget: "boolean"}
#                  - {label: "Text", name: "text", widget: "text"}
#                  - {label: "Number", name: "number", widget: "number"}
#                  - {label: "Markdown", name: "markdown", widget: "markdown"}
#                  - {label: "Datetime", name: "datetime", widget: "datetime"}
#                  - {label: "Date", name: "date", widget: "date"}
#                  - {label: "Image", name: "image", widget: "image"}
#                  - {label: "File", name: "file", widget: "file"}
#                  - {label: "Select", name: "select", widget: "select", options: ["a", "b", "c"]}
#                  - {label: "Hidden", name: "hidden", widget: "hidden", default: "hidden"}
